---
title: "L1 Answers"
author: "Public Health Metrics"
date: "January 8, 2017"
output: html_document
---

```{r L1, echo=FALSE, warning=FALSE, message=FALSE}
#The dataset we are exploring has influenza and pneumonia deaths on a state and national level, over time. 

#We will be requiring knitr, dplyr, and ggplot2
setwd('~/TA stuff/Winter2017/labs/L1-Review/')
require(dplyr)
require(knitr)
require(ggplot2)
require(magrittr) # for pipe operator

#Read in the dataset
deaths <- read.csv('flu_deaths.csv')

#Handle NA values
deaths[is.na(deaths)] <- 0

```

This table shows the number of flu and pneumonia deaths by state for 2016-17, with California having the most deaths and Connecticut having the lowest amount with **0** deaths.

```{r summary, echo=FALSE}

?filter

#Summary table
deaths_summary <- filter(deaths, geoid == "State", season == "2016-17") %>%
                  select(State, season, Deaths.from.pneumonia.and.influenza) %>%
                  group_by(State, season) %>%
                  summarize(num_deaths = sum(Deaths.from.pneumonia.and.influenza)) %>%
                  select(State, num_deaths) %>%
                  arrange(desc(num_deaths))

kable(deaths_summary)

```

